[package]
name = "goose"
version = "0.16.4-dev"
authors = ["Jeremy Andrews <jeremy@tag1consulting.com>"]
edition = "2018"
description = "A load testing framework inspired by Locust."
homepage = "https://tag1.com/goose"
documentation = "https://book.goose.rs"
repository = "https://github.com/tag1consulting/goose"
readme = "README.md"
keywords = ["loadtesting", "performance", "web", "framework", "tool"]
license = "Apache-2.0"

[dependencies]
async-trait = "0.1.57"
chrono = "0.4.19"
ctrlc = "3.2.2"
downcast-rs = "1.2.0"
flume = "0.10.14"
futures = "0.3.21"
gumdrop = "0.8.1"
http = "0.2.8"
itertools = "0.10.3"
lazy_static = "1.4.0"
log = "0.4.17"
num_cpus = "1.13.1"
num-format = "0.4.0"
rand = "0.8.5"
regex = "1.6.0"
reqwest = { version = "0.11.11", default-features = false, features = [
    "cookies",
    "gzip",
    "json",
] }
serde = { version = "1.0.141", features = [
    "derive",
] }
serde_cbor = "0.11.2"
serde_json = "1.0.82"
simplelog = "0.12.0"
strum = "0.24.1"
strum_macros = "0.24.2"
tokio = { version = "1.15.0", features = [
    "fs",
    "io-util",
    "macros",
    "net",
    "rt-multi-thread",
    "time",
    "sync",
] }
tokio-tungstenite = "0.17.2"
tungstenite = "0.17.3"
url = "2.2.2"

# optional dependencies
nng = { version = "1.0.1", optional = true }

[features]
default = ["reqwest/default-tls"]
gaggle = ["nng"]
rustls-tls = ["reqwest/rustls-tls", "tokio-tungstenite/rustls-tls-native-roots"]

[build-dependencies]
rustc_version = "0.4.0"

[dev-dependencies]
httpmock = "0.6.6"
native-tls = "0.2.10"
nix = "0.24.2"
rustls = "0.20.6"
serial_test = "0.8.0"
